### ISSUE TITLE
Misleading role description

### ISSUE THREAD

**Issue by rmsc** [Spredzy/ansible-role-lecm#5]
The role description reads "An Ansible module for ...", while modules are actually a different beast altogether. Could you please change it to "An ansible role for ..."?

As a side note, I found this role while I was looking for an actual Ansible module for letsencrypt.

**Comment by Spredzy** [comment]
Hello @rmsc sorry I missed this issue earlier this year.

You are totally right about the description it has been update.

As for your request:

  * There is a `letsencrypt` module available: https://docs.ansible.com/ansible/2.3/letsencrypt_module.html
  * Also, there is a work currently going on around a new module `openssl_certificate` that would work with different backends (selfsigned, acme - for letsencrypt, ...) It is not currently in the code base but should be featured in 2.4 https://github.com/ansible/ansible/pull/28263

Again sorry for the delay in this answer
