### ISSUE TITLE
support for debian/ubuntu

### ISSUE THREAD

**Issue by oppianmatt** [Spredzy/ansible-role-lecm#6]
Trying to use this on Ubuntu gives an error similar to:

```
FAILED! => {"failed": true, "reason": "the file_name '/x/x/Debian.yml' does not exist, or is not readable"}
```

**Comment by Spredzy** [comment]
Commit https://github.com/Spredzy/ansible-role-lecm/commit/88fe87b03550b92c034df311cae1a8fb4adbca30 fixes this issue.

Note: There are 'official' packages for Debian, while on Ubuntu the pip version will be installed.
